---
title: "Data Preprocessing"
author: "Pin-Chun Chen"
date: "02/14/2021"
output: html_document
---

```{r warning=FALSE, message=FALSE, eval = F, echo=FALSE}
packages.used = as.list(
  c("dplyr", "tibble", "tidyverse", "shinythemes", "shiny", "sf", "RCurl",
    "stringr", "tmap", "tidyr", "ggplot2", "data.table", "ggmap", "DT",
    "choroplethr", "devtools", "DT", "readr", "lubridate", "leaflet", "tigris",
    "emojifont", "viridis", "plotly", "rgdal", "tmap", "RCurl", "tigris")
)
check.pkg = function(x){
  if(!require(x, character.only=T)) install.packages(x, character.only=T, dependence=T)
}

lapply(packages.used, require, character.only = TRUE)
```

```{r}
data_modzcta <- read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/totals/data-by-modzcta.csv")
antibody_by_modzcta <- read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/totals/antibody-by-modzcta.csv")
date_data_modzcta <- read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/latest/pp-by-modzcta.csv")

antibody_by_modzcta <- antibody_by_modzcta %>% rename(ANTIPERSCENT = PERCENT_POSITIVE)
antibody_by_modzcta <- antibody_by_modzcta[, -1:-3]
covid_by_modzcta <- cbind(data_modzcta, antibody_by_modzcta)

date_data_modzcta <- t(date_data_modzcta)
date_data_modzcta <- rbind(date_data_modzcta[8:dim(date_data_modzcta)[1], ])
date_data_modzcta <- data.frame(date_data_modzcta)
data_modzcta_info <- data_modzcta[, 1:4]
date_data_modzcta <- cbind(data_modzcta_info, date_data_modzcta)
date_data_modzcta$data_modzcta_ <- as.character(date_data_modzcta$MODIFIED_ZCTA)
date_data_modzcta$X3 <- as.numeric(date_data_modzcta$X3)


US_zipcode <- zctas(cb = TRUE, starts_with = "1")
US_zipcode <- US_zipcode[as.numeric(US_zipcode$ZCTA5CE10) < 11698, ]

covid_by_modzcta$MODIFIED_ZCTA <- as.character(covid_by_modzcta$MODIFIED_ZCTA)


# join zip boundaries and covid data 
US_zipcode <- geo_join(US_zipcode, 
                       covid_by_modzcta, 
                       by_sp = "GEOID10", 
                       by_df = "MODIFIED_ZCTA",
                       how = "left")

US_date <- geo_join(US_zipcode, 
                       date_data_modzcta, 
                       by_sp = "GEOID10", 
                       by_df = "data_modzcta_",
                       how = "left")

US_zipcode <- na.omit(US_zipcode)

US_zipcode <- US_zipcode[order(US_zipcode$GEOID10), ]

US_zipcode$TOTAL_POSITIVE_TESTS <- floor((US_zipcode$PERCENT_POSITIVE/100)*US_zipcode$TOTAL_COVID_TESTS)

US_zipcode$POP_DENOMINATOR <- floor(US_zipcode$POP_DENOMINATOR)

US_date <- na.omit(US_date)

US_date <- US_date[order(US_date$GEOID10), ]

save.image(file = '../app/output/US_zipcode.RData')
save.image(file = '../app/output/US_date.RData')
```



```{r}
load("../app/output/US_zipcode.RData")
load("../app/output/US_date.RData")
```


